version: "3"

services:
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    hostname: "localhost"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
      